# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldash', '0002_auto_20171026_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='joiner',
            field=models.ManyToManyField(related_name='joined_trips', to='traveldash.Person'),
        ),
    ]
