# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveldash', '0003_auto_20171026_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
