# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldash', '0004_auto_20171026_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joiner',
        ),
        migrations.AddField(
            model_name='trip',
            name='joined',
            field=models.ManyToManyField(related_name='joined_trips', to='traveldash.Person'),
        ),
    ]
